# Ingest Data
First we import all the necessary libraries

In [1]:
import pandas as pd 
from sqlalchemy import create_engine, Integer, DateTime

Now we import the data into a dataframe

In [2]:
# Parquet
taxi_trips_nov2025 = "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet"
#CSV
zone_dataset = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv"

df_taxi_trips = pd.read_parquet(taxi_trips_nov2025)
df_zone = pd.read_csv(zone_dataset)

# First visualization of the data that we are going to use:

In [3]:
df_taxi_trips

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.20,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.00
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.20,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.00
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.50,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.00
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.70,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.00
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.40,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46907,2,2025-11-30 19:58:34,2025-11-30 20:14:28,NaN,NaN,59,51,NaN,8.50,33.22,...,0.5,0.00,0.0,NaN,1.0,34.72,NaN,NaN,NaN,0.00
46908,2,2025-11-30 19:34:00,2025-11-30 19:46:00,NaN,NaN,74,151,NaN,1.73,13.86,...,0.5,0.77,0.0,NaN,1.0,16.13,NaN,NaN,NaN,0.00
46909,2,2025-11-30 21:46:46,2025-11-30 22:17:55,NaN,NaN,33,163,NaN,7.52,38.42,...,0.5,1.00,0.0,NaN,1.0,44.42,NaN,NaN,NaN,0.75
46910,2,2025-11-30 21:00:00,2025-11-30 21:15:00,NaN,NaN,16,95,NaN,5.61,24.67,...,0.5,0.00,0.0,NaN,1.0,26.17,NaN,NaN,NaN,0.00
46911,2,2025-11-30 23:26:00,2025-11-30 23:42:00,NaN,NaN,65,87,NaN,2.91,14.46,...,0.5,3.89,0.0,NaN,1.0,23.35,NaN,NaN,NaN,0.75

In [4]:
df_taxi_trips.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag                  str
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [5]:
df_zone

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                       NV          NaN
264         265        Unknown                      NaN          NaN

[265 rows x 4 columns]

In [6]:
df_zone.dtypes

LocationID      int64
Borough           str
Zone              str
service_zone      str
dtype: object

# Preparing the data for the ingestion into Postgres

In [7]:
# Creating an engine using SQLAlchemy
engine = create_engine('postgresql+psycopg2://root:root@localhost:5432/green_ny_taxi')

Get DDL schema (sql command):

In [8]:
print(pd.io.sql.get_schema(df_taxi_trips, name="green_taxi_data", con=engine))

CREATE TABLE green_taxi_data (
	"VendorID" INTEGER,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" FLOAT(53),
	"PULocationID" INTEGER,
	"DOLocationID" INTEGER,
	passenger_count FLOAT(53),
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type FLOAT(53),
	trip_type FLOAT(53),
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)

Check dtypes:

In [9]:
#To deal with NaN values, Pandas considers columns type as Float instead of Integer
#So we deal with it manually, ensuring that the data type in SQL is as we expected

dtypes = { 
    "VendorID": Integer(),
    "lpep_pickup_datetime": DateTime(),
    "lpep_dropoff_datetime": DateTime(),
    "RatecodeID": Integer(), 
    "passenger_count": Integer(),
    "payment_type": Integer(),
    "trip_type": Integer()
}

Checking again the DDL schema

In [10]:
print(pd.io.sql.get_schema(df_taxi_trips, name="green_taxi_data", con=engine, dtype=dtypes))

CREATE TABLE green_taxi_data (
	"VendorID" INTEGER,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" INTEGER,
	"PULocationID" INTEGER,
	"DOLocationID" INTEGER,
	passenger_count INTEGER,
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type INTEGER,
	trip_type INTEGER,
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)

Now we check the schema structure is correctly created:

In [11]:
df_taxi_trips.head(0).to_sql(name="green_taxi_data", con=engine, if_exists = "replace")
# 0 means it works

0

# Finally, we ingest the data into PostgresQL

In [12]:
df_taxi_trips.to_sql(name="green_taxi_data", con=engine, if_exists = "append")

912

We check if everything works:

In [13]:
check = pd.read_sql("SELECT * FROM green_taxi_data LIMIT 10;", con = engine)
print(check)

   index  VendorID lpep_pickup_datetime lpep_dropoff_datetime  \
0      0         2  2025-11-01 00:34:48   2025-11-01 00:41:39
1      1         2  2025-11-01 00:18:52   2025-11-01 00:24:27
2      2         2  2025-11-01 01:03:14   2025-11-01 01:15:24
3      3         2  2025-11-01 00:10:57   2025-11-01 00:24:53
4      4         1  2025-11-01 00:03:48   2025-11-01 00:19:38
5      5         1  2025-11-01 00:42:13   2025-11-01 01:04:50
6      6         2  2025-11-01 00:05:41   2025-11-01 00:39:20
7      7         2  2025-11-01 00:42:14   2025-11-01 01:13:20
8      8         2  2025-11-01 00:03:08   2025-11-01 00:06:27
9      9         2  2025-11-01 00:56:33   2025-11-01 01:01:34

  store_and_fwd_flag  RatecodeID  PULocationID  DOLocationID  passenger_count  \
0                  N         1.0            74            42              1.0
1                  N         1.0            74            42              2.0
2                  N         1.0            83           160              1.0
3                  N         1.0           166           127              1.0
4                  N         1.0           166           262              1.0
5                  N         1.0           112            48              2.0
6                  N         1.0            83            87              1.0
7                  N         1.0            66           233              1.0
8                  N         1.0           223           223              1.0
9                  N         1.0           130           130              1.0

   trip_distance  ...  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0           0.74  ...      0.5        1.94           0.0       None
1           0.95  ...      0.5        0.00           0.0       None
2           2.19  ...      0.5        5.00           0.0       None
3           5.44  ...      0.5        0.50           0.0       None
4           3.20  ...      1.5        1.00           0.0       None
5           5.10  ...      1.5        6.55           0.0       None
6           9.80  ...      0.5        9.92           0.0       None
7           5.01  ...      0.5        6.98           0.0       None
8           0.63  ...      0.5        1.52           0.0       None
9           1.15  ...      0.5        0.00           0.0       None

   improvement_surcharge total_amount  payment_type  trip_type  \
0                    1.0        11.64           1.0        1.0
1                    1.0         9.70           2.0        1.0
2                    1.0        21.00           1.0        1.0
3                    1.0        27.70           1.0        1.0
4                    1.0        24.65           1.0        1.0
5                    1.0        39.35           1.0        1.0
6                    1.0        59.52           1.0        1.0
7                    1.0        41.88           1.0        1.0
8                    1.0         9.12           1.0        1.0
9                    1.0        10.40           2.0        1.0

   congestion_surcharge  cbd_congestion_fee
0                  0.00                0.00
1                  0.00                0.00
2                  0.00                0.00
3                  0.00                0.00
4                  2.75                0.00
5                  2.75                0.75
6                  2.75                0.75
7                  2.75                0.75
8                  0.00                0.00
9                  0.00                0.00

[10 rows x 22 columns]

Number of rows:

In [14]:
rows_number = pd.read_sql("SELECT COUNT(1) FROM green_taxi_data;", con = engine)
print(rows_number)

   count
0  46912